### ISSUE TITLE
[Question] Fish-eye

### ISSUE THREAD

**Issue by pedromlsreis** [tfaehse/DashcamCleaner#1]
Hello, great job you did here!

I've got one question - was this model trained using fish-eye or non-fish-eye dashcam images?
Plus, how do you expect it to behave facing fish-eye videos from a GoPro?

Thank you.
Pedro

**Comment by tfaehse** [comment]
Hi Pedro, thank you for your interest!

The model was unfortunately trained exclusively with data from a 70mai 1S dashcam. While it does have a wide FOV, I wouldn’t consider it a fisheye camera at all, so performance with GoPro data would most likely not be optimal. 
I intend to rerun training with more data later, fisheye sources sound like a great idea!
