### ISSUE TITLE
weights not found

### ISSUE THREAD

**Issue by joshinils** [tfaehse/DashcamCleaner#19]
https://github.com/tfaehse/DashcamCleaner/blob/caddcb80d0aed082285fa36865363cd323899a20/dashcamcleaner/src/blurrer.py#L22
The problem is that path gets treated as a relative path, not as an absolute path.
So the only place one can run the code from is the folder in the cloned repo, nowhere else.

doesn't depend on main.py or cli.py

**Comment by tfaehse** [comment]
*Should* be fixed, we now look at the weights folder relative to the location of the file the tool is run from. If issues persist feel free to reopen this issue of course!
