### ISSUE TITLE
Error blurrer

### ISSUE THREAD

**Issue by Dave04O4** [tfaehse/DashcamCleaner#48]
Hello, 

I had 4 errors, but unfortunately I could not fix the 2 errors yet.

```
Traceback (most recent call last):
  File "d:\Dashcam\D1\src\qt_wrapper.py", line 72, in run
    frame_blurred = self.apply_blur(frame, detections)
  File "d:\Dashcam\D1\src\blurrer.py", line 50, in apply_blur
    export_colored_mask = self.parameters["export_colored_mask"]
KeyError: 'export_colored_mask'
```

Cache was cleared and I also reinstalled the PC.

**Comment by tfaehse** [comment]
Hi! Thank you for the report, this one is clearly on me and not on your system/installation. The linked PR should fix the issue, if you encounter anything else please reopen/create a new issue!
