### ISSUE TITLE
Avoid GUI

### ISSUE THREAD

**Issue by irdalan** [tfaehse/DashcamCleaner#8]
Is it possible to use your tool without the GUI provided, but giving the input arguments through command line? It would be great because:
1) If one uses your repository on a Linux machine to which he connects via ssh from a windows computer, the application fails.
2) It would be easier to automate different input configurations to assess which one is the most suited for a specific case

**Comment by tfaehse** [comment]
That's a nice idea! I'll get started on that fairly soon

**Comment by tfaehse** [comment]
Should be functional now, but it's a bit rough - there is no progress bar, but that shouldn't be too hard to add later. For now it works at least, make sure to provide all parameters when calling it.
